Name:		texlive-ccool
Version:	60600
Release:	2
Summary:	A key-value document command parser
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/macros/latex/contrib/ccool
License:	lppl1.3c
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/ccool.r%{version}.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/ccool.doc.r%{version}.tar.xz
Source2:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/ccool.source.r%{version}.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
This package provides a key-value interface, \Ccool, on top of
xparse's document command parser. Global options control input
processing and its expansion. By default, they are set to meet
likely requirements, depending on context: the selected
language, and which of text and math mode is active. These
options can be overridden inline. This versality could find its
use, for example, to encode notational conventions (such as
\Real - \mathbb{R}) at the point where they are introduced in
the document ("Let R denote real numbers"). Polymorphic
commands can be generated by parameterizing the keys (for
instance, one parameter value for style, another for a
property). User input to \Ccool can optionally be serialized.
This can useful for typesetting documents sharing the same
notation.

%prep
%setup -c -a1 -a2
%autopatch -p1

%build

%install
rm -rf tlpkg
mkdir -p %{buildroot}%{_texmfdistdir}
cp -a * %{buildroot}%{_texmfdistdir}

%files
%doc %{_texmfdistdir}/source/latex/ccool
%{_texmfdistdir}/tex/latex/ccool
%doc %{_texmfdistdir}/doc/latex/ccool

%post -p %{_sbindir}/texlive.post

%postun
[ "$1" -eq 0 ] && %{_sbindir}/texlive.post
