%global tl_name ccool
%global tl_revision 76924

Name:		texlive-%{tl_name}
Epoch:		1
Version:	3.2
Release:	%{tl_revision}.1
Summary:	A key-value document command parser
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/macros/latex/contrib/ccool
License:	lppl1.3c
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/ccool.r%{tl_revision}.tar.xz
Source1:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/ccool.doc.r%{tl_revision}.tar.xz
Source2:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/ccool.source.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
This package provides a key-value interface, \Ccool, on top of xparse's
document command parser. Global options control input processing and its
expansion. By default, they are set to meet likely requirements,
depending on context: the selected language, and which of text and math
mode is active. These options can be overridden inline. This versatility
could find its use, for example, to encode notational conventions (such
as \Real - \mathbb{R}) at the point where they are introduced in the
document ("Let R denote real numbers"). Polymorphic commands can be
generated by parameterizing the keys (for instance, one parameter value
for style, another for a property). User input to \Ccool can optionally
be serialized. This can useful for typesetting documents sharing the
same notation.

